language: c

env:
  global:
    - secure: "ffn0Fo4WZjGg1HYL6e4iAFsGcBcyTYK63Y3fIr/cJsoWjylbjYoIgpqWsgC9J/FCpxb2cqdQkzVXR+GSJQ5y7pBj59UXCxkxTIs3z3D2O2YqhvpmHZE8VPQY8qyJl9jf5oilJ30opDwVEf/yU11x+YpRWlhUf3J0GD+GnZDFaH6wUIBtop9RAOaLrfnaKXCinXT2XEOpmfKqNzbomCmz9O7QP2xVVJGPvwkynQb8pRKiu2T79lqKT/eRv1R6pf0ZnPwy36JFll8z+oMqH94ftOcfz2md4RJXD92ea61gmhzfqG5DI9IPhz63UO5wI0mN5eMQUFiqoMKVq/B82DcIUYfQzUrnhI93NxzIyrjHPEzpLJYyKow6B1krpQv+9W9Vd2Ys7H5sRAVIsuKQMsBKerDZtTVDlHppM27OGFD04VHykLHEdeOCOi/ls8SXedlwLMVmD9aMe5n0lKmDvD95esTIoGWVJqKBSej7mjPzVoLwRsIurBnn3D/RJ4cUo4ib4zxJf3/m7KhkcuRuA19hK0pqkSwm7c9i52hBfwDfdYM03xsENGJw+/OUh5RX2y4DuMWkDKFdghe4r+BO9cZ3vRLwHhs7dq+20mJ2jKHa0ypT1kMGmrUKuBteD49lt/Fp2nlhf2M8TiAwoRPUF+sCE0KY98SzgTjPlIwpff6gQ58="


before_install:
  - sudo dpkg --purge cmake cmake-doc cmake-data
  - curl http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04 ./" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install mingw64-lua51-wxlua
  - sudo apt-get --assume-yes install cmake3
  - sudo apt-get --assume-yes install python-pip python-virtualenv
  - virtualenv ~/virtualenv/python2.7
  - source ~/virtualenv/python2.7/bin/activate
  - pip install -q requests


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - ./.build.sh


after_success:
  - python installer/ivy/deploy.py build/artifacts/artifacts_wxlua.xml


deploy:
  provider: releases
  api_key:
    secure: mrw32k5aKAP2p/1RnkNGKa9Gc2Vu3bASqb3ryiCWNif22RLuCts2eMwTr2mPnc/umRVYyHqggPJf+BcPkvAgxgwo4paN7JwED35RMDSP+ghLEcPQyS7VEj5SrWqF9vYm9AZ6pw8aTqLvemgdcjMJa/jzJ/UtovLq79vJ+i+SqBw=
  file:
    - build/lua51-wxlua.zip
    - build/ivy.xml
  skip_cleanup: true
  on:
    repo: muhkuh-sys/org.muhkuh.lua-wxlua
    tags: true
